### PR TITLE
Improve wizard provider forms handling and fix node data caching issue

### LINKED ISSUE #3576: [Wizard] Improve Openstack form handling

### LINKED ISSUE #3577: [Wizard] Improve KubeVirt form handling

### LINKED ISSUE #3578: [Wizard] Improve Packet form handling

### LINKED ISSUE #3579: [Wizard] Improve VSPhere form handling

### LINKED ISSUE #3599: Node data cache is not cleared
**What happened?**: Open dev.kubermatic.io in a new tab, login, go to some project and try to create new AWS cluster. After picking provider and datacenter you will be redirected to the next step (it works correctly).

Now, try to do the same but after login go to existing AWS cluster, open add MD dialog, cancel and then go to the wizard. After picking AWS and some datacenter you will see that the next step is disabled and there are multiple errors in the browser console.

Zrzut ekranu 2021-08-9 o 12 58 44

**What should happen?**: There should be no errors.

**How to reproduce?**: As above.

**Environment**
- UI Version: master
- API Version: master
- Domain: dev
- Others: Chrome

### PR DESCRIPTION
**Pull request by floreks**
### What this PR does / why we need it
- Improve remaining wizard provider forms handling
- Add proper error mappings for the specific providers
- Fix data caching issue when using add node deployment dialog and then the wizard

### Which issue(s) this PR fixes

Fixes #3576
Fixes #3577
Fixes #3578
Fixes #3579 
Fixes #3599

### Release note

```release-note
NONE
```

### CODE REVIEW

File: src/app/core/interceptors/error-notifications.ts [hunk 1]
```diff
@@ -43,6 +43,10 @@ export class ErrorNotificationsInterceptor implements HttpInterceptor {
     ['Unauthorized', Errors.InvalidCredentials],
     ['validate the provided access credentials', Errors.InvalidCredentials],
     ['Unable to authenticate you', Errors.InvalidCredentials],
+    ['Authentication failed', Errors.InvalidCredentials],
+    ["couldn't get auth client", Errors.InvalidCredentials],
```
Comment (maciaszczykm) [inline src/app/core/interceptors/error-notifications.ts:47]: It's minor but the quotation marks are different here. Not a blocker.
