### PR TITLE
fixed quota widget logic

### LINKED ISSUE #4892: Quota widget not displayed when CPU quota is not configured
### What happened

If CPU quota is not configured then Project Overview and Cluster Wizard don't display quotas.

**Only Memory and Disk quotas are configured:**
screenshot-localhost_8000-2022 08 24-21_52_10

**Project Overview Page:**

screenshot-localhost_8000-2022 08 24-21_33_44

**Cluster Wizard**

screenshot-localhost_8000-2022 08 24-21_33_12

### Expected behavior
Quotas should be displayed with availalbe information similar to how its displayed on Clusters page.

### How to reproduce
Configure quotas for a project and keep CPU quota empty.

### PR DESCRIPTION
**Pull request by Talha-Jamil-TJ**
**What this PR does / why we need it**:

Fixed quota widget not being rendered when `CPU` is not set on project overview page and Initial nodes cluster step.

**Which issue(s) this PR fixes**:

Fixes #4892

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: src/app/project-overview/component.ts [hunk 1]
```diff
@@ -83,10 +90,16 @@ export class ProjectOverviewComponent implements OnInit, OnDestroy {
...
     private readonly _cookieService: CookieService
-  ) {}
+  ) {
+    if (this.isEnterpriseEdition) {
+      this._quotaService = GlobalModule.injector.get(QuotaService);
+    }
+  }
 
   ngOnInit(): void {
+    this._setProjectId();
```
Comment (Waseem826) [inline src/app/project-overview/component.ts:102]: Is this method recalled if I select different project from top nav bar?

Comment (Waseem826) [reply src/app/project-overview/component.ts:102]: Looks like we have same issue on clusters page as well (if cluster is set as default landing page)


https://user-images.githubusercontent.com/13975988/186639214-3c751242-cbdd-4d0b-b90f-beaf25b79ad4.mov

Comment (Talha-Jamil-TJ) [reply src/app/project-overview/component.ts]: No, I've updated logic for catering to that condition.

Comment (Waseem826) [reply src/app/project-overview/component.ts]: @Talha-Jamil-TJ what about clusters page issue?

File: src/app/project-overview/component.ts [hunk 2]
```diff
@@ -109,6 +118,10 @@ export class ProjectOverviewComponent implements OnInit, OnDestroy {
     component.projectId = this.project.id;
     component.showQuotaWidgetDetails = true;
     component.showIcon = false;
+
+    this._projectChange.pipe(takeUntil(this._unsubscribe)).subscribe(_ => {
+      component.projectId = this.project.id;
```
Comment (Waseem826) [inline src/app/project-overview/component.ts:123]: Should we implement `ngOnChanges` in quota-widget component so that it immediately reloads quotas if `projectId` is changed?

Comment (Talha-Jamil-TJ) [reply src/app/project-overview/component.ts:123]: Alright

**Review by Waseem826 — APPROVED** [review]
/approve
