### PR TITLE
Fix the redirect url for keycloak logout

### LINKED ISSUE #6127: Logout url does not work with Keycloak 18.0 or higher
### What happened

The oidc logout url feature in the ui configuration is unsuitable because it hardcodes `redirect_uri` to append to the logout url. This does not work with Keycloak 18 or higher.

See [Keycloak OpenID logout documentation](https://www.keycloak.org/docs/latest/upgrading/index.html#openid-connect-logout) for details on what parameters are required.

When you actually try to configure it, you get

> Invalid parameter: redirect_uri

when clicking logout.

### Expected behavior

Keycloak logout flow is supported or to be more precise, ui configuration needs to be flexible enough to allow configuration for the Keycloak logout flow.

### Environment
- UI Version: v2.22.4
- API Version: v2.22.4
- Domain:
- Others: Keycloak 18.0+

### Current workaround

None known.

### Affected user persona

Users with Keycloak as OIDC solution.

### PR DESCRIPTION
**Pull request by ahmadhamzh**
**What this PR does / why we need it**:
Starting from Keycloak 18, [RP initiated logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout) was introduced in keycloak. `post_logout_redirect_uri` and `id_token_hint` parameters are required now for logging a user out. 

To support this special case, we are now adding a new configuration named `oidc_provider` which will allow us to manage OIDC provider specific configurations.

**Which issue(s) this PR fixes**:
Fixes #6127

**What type of PR is this?**

/kind bug

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fix support for keycloak OIDC logout. New field `oidc_provider` was introduced to support OIDC provider specific configurations. Configuring `oidc_provider` as `keycloak` will properly configure the logout workflow.
```

**Documentation**:

```documentation
TBD
```

### CODE REVIEW

File: modules/web/src/app/core/services/auth/service.ts [hunk 1]
```diff
@@ -130,10 +130,16 @@ export class Auth {
...
+      if( urlArr.includes('realms')) {
+          logoutUrl.searchParams.set('post_logout_redirect_uri', this._redirectUri);
+          logoutUrl.searchParams.set('id_token_hint', this.getBearerToken());
+      }else {
+        if (logoutUrl.searchParams.has('redirectUri')) {
+          logoutUrl.searchParams.set('redirectUri', this._redirectUri);
+        } else {
+          logoutUrl.searchParams.set('redirect_uri', this._redirectUri);
+        }
       }
```
Comment (ahmedwaleedmalik) [inline modules/web/src/app/core/services/auth/service.ts:143]: Realm name is always there since the keycloak clients are always scoped to a realm. The only case otherwise is when you are using some proxy in front of keycloak to obscure the realm name or the keyloak URL. 

So i'm not sure how we are making decision regarding parameters based on the presence of `realm` within the URL?

**Review by ahmedwaleedmalik — CHANGES_REQUESTED** [review]

File: modules/web/src/app/core/services/auth/service.ts [hunk 2]
```diff
@@ -130,10 +130,16 @@ export class Auth {
...
       const logoutUrl = new URL(config.oidc_logout_url);
-      if (logoutUrl.searchParams.has('redirectUri')) {
-        logoutUrl.searchParams.set('redirectUri', this._redirectUri);
-      } else {
-        logoutUrl.searchParams.set('redirect_uri', this._redirectUri);
+      const urlArr = config.oidc_logout_url.split('/');
+      if( urlArr.includes('realms')) {
+          logoutUrl.searchParams.set('post_logout_redirect_uri', this._redirectUri);
+          logoutUrl.searchParams.set('id_token_hint', this.getBearerToken());
+      }else {
```
Comment (ahmedwaleedmalik) [inline modules/web/src/app/core/services/auth/service.ts:137]: Please fix the indentations here.

File: modules/web/src/app/project/template.html [hunk 3]
```diff
@@ -374,11 +374,11 @@ <h2>Get Started</h2>
...
 <ng-template #allProjectToggle>
   <mat-slide-toggle *ngIf="isAdmin"
-                        class="all-projects-toggle"
-                        [disabled]="isProjectsLoading"
-                        labelPosition="before"
-                        [matTooltip]="isProjectsLoading ? 'Please wait while projects are loading' : null"
-                        [ngModel]="settings.displayAllProjectsForAdmin"
-                        (toggleChange)="changeProjectVisibility()">Show All Projects
+                    class="all-projects-toggle"
+                    [disabled]="isProjectsLoading"
```
Comment (ahmedwaleedmalik) [inline modules/web/src/app/project/template.html:378]: Do we know why these issues with indentations are not being caught by our pipelines? It seems like a common occurrence these days. Because these should have been already fixed in the last PR where these files were modified. 

I noticed this issue a few weeks ago as well.

An example from your own PR would be https://github.com/kubermatic/dashboard/pull/6144/files#diff-1f46f73009b38ea4ecfc48cd53babc9b1f45fb74a441dbab8cd538c1c1c8a190R134, CI should have complained about this.

File: modules/web/src/app/core/services/auth/service.ts (hunk 1 above)
Comment (ahmadhamzh) [reply modules/web/src/app/core/services/auth/service.ts:143]: how about we use a new value in the `config` like `config.oidc_provider` ? or something ?
@Waseem826 @ahmedwaleedmalik

**Comment by xrstf** [comment]
I just have to say it, sorry, but:

It's **keycloak**, not keyclock.

Thank you. ;-)

File: modules/web/src/app/core/services/auth/service.ts [hunk 4]
```diff
@@ -130,10 +130,18 @@ export class Auth {
     const config = this._appConfigService.getConfig();
     if (config.oidc_logout_url) {
       const logoutUrl = new URL(config.oidc_logout_url);
-      if (logoutUrl.searchParams.has('redirectUri')) {
-        logoutUrl.searchParams.set('redirectUri', this._redirectUri);
-      } else {
-        logoutUrl.searchParams.set('redirect_uri', this._redirectUri);
+      switch (config.oidc_provider?.toLowerCase()) {
+        case 'keyclock':
```
Comment (ahmedwaleedmalik) [inline modules/web/src/app/core/services/auth/service.ts:134]: Please create a constant somewhere for this and don't hard-code it here. Also `s/keyclock/keycloak`.

**Review by ahmedwaleedmalik — CHANGES_REQUESTED** [review]

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
@ahmadhamzh You'll have to manually backport this PR to 2.23, 2.22, 2.21. Also please ensure that the documentation makes its way into those versions as well before the next patch releases.
