### PR TITLE
External Cluster Fixes

### LINKED ISSUE #4876: External cluster form doesnt get reset
### What happened
If you select a provider , go back and select another provider all the required fields show as error below even without selecting any input field
required

add hints:
- EKS Cluster Role for Create Wizard: Add hint `Enter the IAM role arn to allow the Kubernetes control plane to manage AWS resources on your behalf. To get or create a cluster service role <Amazon EKS User Guide>
(https://docs.aws.amazon.com/eks/latest/userguide/service_IAM_role.html) `

- EKS MD :Node IAM role
`Enter the IAM role arn that will be used by the nodes. To get or create a node role <Amazon EKS User Guide> (https://docs.aws.amazon.com/eks/latest/userguide/create-node-role.html)`

- AKS Resource Group: 
`Enter the name of the resource group. The resource group should have sufficient permissions to manage AKS cluster <AKS RBAC Guide> (https://docs.microsoft.com/en-us/azure/aks/concepts-identity#azure-rbac-to-authorize-access-to-the-aks-resource). To get or create a resource group
 <Azure User Guide> https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal`

- EKS and AKS version hint -> `Enter or Select Kubernetes Version`

- Add hint for Service Account (Import/Create) for GKE -> `Enter base64 encoded value for ServiceAccount`

- `releaseChannel` value for GKE external cluster wizard. [Release Channel](https://github.com/kubermatic/kubermatic/pull/10831/files)

### Environment
- UI Version:
- API Version:
- Domain:
- Others:

### PR DESCRIPTION
**Pull request by KhizerRehan**
**What this PR does / why we need it**:

This PR adds 
- UI fixes (hint fixes) along with this adds payload fixes for GKE cluster. 
- It also handles state for fields which has network call dependency to update user some actions is been done.
- Updates text for dialogs (Disconnect/Delete)

**Which issue(s) this PR fixes**:

Fixes #4876 

/kind bug
/kind cleanup

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
None
```

**Documentation**:

```documentation
None
```

### CODE REVIEW

File: src/app/external-cluster-wizard/component.ts [hunk 1]
```diff
@@ -33,15 +33,16 @@ import {ExternalClusterWizardStep, StepRegistry, WizardSteps} from './config';
   styleUrls: ['./style.scss'],
 })
 export class ExternalClusterWizardComponent implements OnInit, OnDestroy {
-  private readonly _unsubscribe = new Subject<void>();
   readonly stepRegistry = StepRegistry;
   readonly externalProviders = [ExternalClusterProvider.AKS, ExternalClusterProvider.EKS, ExternalClusterProvider.GKE];
   form: FormGroup;
   project = {} as Project;
-
+  isInValid = true;
```
Comment (Waseem826) [inline src/app/external-cluster-wizard/component.ts:40]:
```suggestion
  isInvalid = true;
```

File: src/app/external-cluster-wizard/component.ts [hunk 2]
```diff
@@ -140,10 +127,35 @@ export class ExternalClusterWizardComponent implements OnInit, OnDestroy {
...
+        return true;
+    }
+  }
+
   private _initForm(steps: ExternalClusterWizardStep[]): void {
     const controls = {};
     steps.forEach(step => (controls[step.name] = this._builder.control('')));
     this.form = this._builder.group(controls);
+
+    this.form.valueChanges.subscribe(_ => {
```
Comment (Waseem826) [inline src/app/external-cluster-wizard/component.ts:155]:
```suggestion
    this.form.valueChanges.pipe(takeUntil(this._unsubscribe)).subscribe(_ => {
```

File: src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts [hunk 3]
```diff
@@ -73,6 +73,11 @@ enum Mode {
   User = 'User',
 }
 
+export enum LocationState {
```
Comment (Waseem826) [inline src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts:76]: Should we have a 3rd state for no locations? Same comment for other states being added in this PR. This can be enhanced in future so if you think it will more time please create an issue.

File: src/app/shared/components/external-cluster-credentials/preset/component.ts [hunk 4]
```diff
@@ -49,6 +50,8 @@ export enum PresetsState {
 export class CredentialsPresetsComponent extends BaseFormValidator implements OnInit, OnDestroy {
   presetList = new SimplePresetList();
   presetsLoaded = false;
+  selectedProviderPreset: ExternalClusterProvider;
```
Comment (Waseem826) [inline src/app/shared/components/external-cluster-credentials/preset/component.ts:53]:
```suggestion
  selectedProvider: ExternalClusterProvider;
```

File: src/app/shared/components/external-cluster-credentials/preset/component.ts [hunk 5]
```diff
@@ -84,6 +87,11 @@ export class CredentialsPresetsComponent extends BaseFormValidator implements On
     this._externalClusterService.providerChanges
       .pipe(
         filter(provider => !!provider),
+        tap(provider => {
+          if (provider !== this.selectedProviderPreset) {
```
Comment (Waseem826) [inline src/app/shared/components/external-cluster-credentials/preset/component.ts:91]: We should update `this.selectedProvider` here.

File: src/app/shared/components/external-cluster-credentials/preset/component.ts [hunk 6]
```diff
@@ -99,7 +107,10 @@ export class CredentialsPresetsComponent extends BaseFormValidator implements On
     this.form
       .get(Controls.Preset)
       .valueChanges.pipe(takeUntil(this._unsubscribe))
-      .subscribe(preset => (this._externalClusterService.preset = preset));
+      .subscribe(preset => {
+        this._externalClusterService.preset = preset;
+        this.selectedProviderPreset = preset;
```
Comment (Waseem826) [inline src/app/shared/components/external-cluster-credentials/preset/component.ts:112]:
```suggestion

```

File: src/app/shared/components/external-cluster-credentials/provider/aks/template.html [hunk 7]
```diff
@@ -22,6 +22,10 @@
            [formControlName]="Controls.TenantID"
            autocomplete="off"
            required>
+    <mat-hint>
+      Enter Azure Tenant ID.To create one
```
Comment (Waseem826) [inline src/app/shared/components/external-cluster-credentials/provider/aks/template.html:26]:
```suggestion
      Enter Azure Tenant ID. To create one
```
Please also fix this in other changes in this PR below.

**Review by Waseem826 — CHANGES_REQUESTED** [review]
Some minor changes. PTAL

File: src/app/core/services/external-machine-deployment.ts [hunk 8]
```diff
@@ -132,8 +132,8 @@ export class ExternalMachineDeploymentService {
   ): Observable<boolean> {
     const dialogConfig: MatDialogConfig = {
       data: {
-        title: 'Delete Machine Deployment',
-        message: `Delete <b>${md.name}</b> machine deployment of <b>${cluster.name}</b> cluster permanently?`,
+        title: `Delete ${cluster?.cloud.eks ? 'Node Group' : 'Node Pool'}`,
```
Comment (ahmadhamzh) [inline src/app/core/services/external-machine-deployment.ts:135]: do we need to tell the user that the node will be remove from the cloud provider’s end?

File: src/app/core/services/external-machine-deployment.ts [hunk 9]
```diff
@@ -132,8 +132,8 @@ export class ExternalMachineDeploymentService {
...
+        message: `Delete <b>${md.name}</b> of <b>${cluster.name}</b> cluster permanently?`,
```
Comment (ahmadhamzh) [inline src/app/core/services/external-machine-deployment.ts:136]: do we need to tell the user that the node will be remove from the cloud provider’s end? like in the cluster deletion

Comment (KhizerRehan) [reply src/app/core/services/external-machine-deployment.ts:136]: hmm, but that is cluster only, where we can disconnect but in case of MD deletion it will always be deleted

File: src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts (hunk 3 above)
Comment (KhizerRehan) [reply src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts:76]: I think we didn't need 3rd state since Placeholder for Ready (when list) exists or Empty we need to show same but yes we can can create if need to show 3rd state WDYT?

Comment (Waseem826) [reply src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts:76]: In regular cluster wizard we have 3 states for all dropdowns.

Comment (KhizerRehan) [reply src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts:76]: Than i will be creating a sep ticket to manage in all other places too. Thanks

File: src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html [hunk 10]
```diff
@@ -52,34 +52,54 @@
...
                      [options]="kubernetesVersions"
                      [formControlName]="Controls.Version">
       <ng-container hint>
-        Set the kubernetes version.
+        Enter or Select Kubernetes Version
       </ng-container>
     </km-autocomplete>
 
+    <ng-template #dialogViewKubernetesVersion>
+      <mat-form-field *ngIf="isDialogView()">
```
Comment (ahmadhamzh) [inline src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html:66]: do we need this condition here since we using `else` in line 55

Comment (KhizerRehan) [reply src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html:66]: hmm may be correct

**Comment by ahmadhamzh** [comment]
i tested it and it looks good

**Review by Waseem826 — APPROVED** [review]
