### PR TITLE
UI/UX fixes

### LINKED ISSUE #2698: UI/UX Fixes
### Requested Fixes/Changes
- [x] Dropdown arrow really tiny
image

- [x] Global: Code Line Break, change to this kind of behavior if possible? wraps but shows theres no actual linebreak with the numbers
  image
- [x] Global: let's switch out digital ocean, hetzner, openstack, azure and vsphere to svgs
- [x] User Settings: Name to E-Mail spacing gone
- [x] Projects: project card view spacing between icons and data is gone
- [x] Cluster Page: RBAC & Events Spacing on bottom of headline should be same as to the top of the card
- [x] Cluster Create/Provider: Provider/Datacenter headline bottom spacing is larger than on the next step 
- [x] Cluster Create/Cluster: specification kubernetes/openshift switcher height should be same as textfield next to it
- [x] Cluster Create/Cluster: Audit logging too much spacing on top (remove 1 x 16px margin?)
- [x] Cluster Create/Initial Nodes: Remove hover + click effect on provider tags (DigitalOcean) (because it has no functionality)
- [x] Cluster Create/Initial Nodes: upgrade system on first boot add 20px spacing to dynamic kubelet config
- [x] Cluster Create/Settings: Right align SSH Key add button (relative to ssh key dropdown/left column)
- [x] Cluster/MachineDeployment: Upgrade system on the first boot, remove padding-bottom: 8px
- [x] Members: add tooltip over hovering over yourself on member page, on the edit and delete icon "You cannot edit your own data and permissions." 
- [x] SSH Keys: Add Dialogue, rename "Key" field to "Public SSH Key" and remove hint
- [x] Monaco editor cursor is misplaced when typing
- [x] Search/filter outline should stay blue until there is a query inside

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Related to #2698 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
/assign @kgroschoff 

Can you review Kristin? I will do the wizard fixes from the separate pull request as it is taking a bit longer.

File: src/app/shared/components/editor/component.ts [hunk 1]
```diff
@@ -46,6 +46,7 @@ export class EditorComponent implements OnInit {
     scrollbar: {vertical: 'hidden'},
     hideCursorInOverviewRuler: true,
     renderLineHighlight: 'none',
+    wordWrap: 'on',
```
Comment (kgroschoff) [inline src/app/shared/components/editor/component.ts:49]: I'm not sure, if this is easily fixable, but I noticed that the indentation is not given once the line is too long, see:

editor

On the other hand if you already have like 4-5 indentations, the text will be very short.... but for a few indentations it might look a bit more organized? 🤔 

Also I noticed, that the editor has some "problems" when you directly want to place the cursor via mouse. It looks like it is on the given place, but in reality it isn't.... But this is probably not part of this PR 😅

**Review by kgroschoff — COMMENTED** [review]
Just two smaller remarks. Apart from that it looks good 👍

File: src/app/shared/components/editor/component.ts (hunk 1 above)
Comment (maciaszczykm) [reply src/app/shared/components/editor/component.ts:49]: > I'm not sure, if this is easily fixable, but I noticed that the indentation is not given once the line is too long, see:

This is expected in my opinion.

Comment (maciaszczykm) [reply src/app/shared/components/editor/component.ts:49]: > Also I noticed, that the editor has some "problems" when you directly want to place the cursor via mouse. It looks like it is on the given place, but in reality it isn't.... But this is probably not part of this PR 

Yep, I will report an issue for that.

File: src/app/member/member.component.html [hunk 2]
```diff
@@ -76,15 +76,15 @@
               <ng-container *ngSwitchCase="false">
                 <button mat-icon-button
                         [attr.id]="'km-edit-member-' + element?.email"
-                        matTooltip="Edit Member"
+                        [matTooltip]="getEditTooltip(element)"
```
[the remark this answers is not in the document]
Comment (maciaszczykm) [reply src/app/member/member.component.html:79]: I will check that.

File: src/app/shared/components/editor/component.ts (hunk 1 above)
Comment (kgroschoff) [reply src/app/shared/components/editor/component.ts:49]: Okay, I just noticed it and was wondering if it is expected or if it might look a bit more organized to align everything the same (and on the other hand noticed that many indentations might cause very short text in a row) 👍 

Though this is not a blocker :)

Comment (maciaszczykm) [reply src/app/shared/components/editor/component.ts:49]: Sure, I think this may be caused by the removal of the !important rules and refactoring that we did some time ago.

**Comment by maciaszczykm** [comment]
@kgroschoff I've updated https://github.com/kubermatic/dashboard/issues/2698 and fixed the tooltip issue, PTAL :)

**Comment by kgroschoff** [comment]
Great 👍 
/lgtm
