### PR TITLE
Show progress bars when defaulting is applied to projects

### LINKED ISSUE #5594: Display progress bars and details on widget when default project quota are configured
### What happened
Currently, When Default Project Quota is backend sets 0 value for **Quota Variables (cpu, memory, storage)** which resulted into not displaying of progress bars and card details on hover and due to conditional checks on UI "0, null, undefined" values are treated as falsy values.

### How to reproduce
- Navigate to "/settings/quotas"
- Better to select any project and delete quotas if already configured.
- Now try to apply defaulting on project quotas. e.g Update (CPU to 2)
- Backend sets following values 

```
{
	...
	quota: {
	    "cpu": 2,
	    "memory": 0,
	    "storage": 0
	}
}
```

which resulted into not display of progress bars and details as per widget implementation.

### Expected behavior
As per discussion with @lsviben we need to cater case-2 but based on implementation deduced 3 cases as listed below

We have 3 scenarios on quotas

**Case-1:**
- Project with no Quotas should display "No quotas configured"

**Case-2:**
- Project with **default** quotas configured. It should show progress bar and details on hover but it should show 
0/0 GB e.g based on above payload it should be like this:

39d2b6840b4abaa6cd613891aaace1e0

**Case-3:**
- Project with **explicit** quotas configured. It should show progress bar and details on hover for configured properties as there is no "Default" label user has set resources explicitly.

It should show **only**
- configured progress bars
- configured details on card hover

### PR DESCRIPTION
**Pull request by KhizerRehan**
**What this PR does / why we need it**:
This PR cover couple of scenarios:
- Case when no quotas configured
-  Case when explicit quotas configured
- Case when defaulting quotas configured

**Explicit:**

https://user-images.githubusercontent.com/17727069/214517759-45dc7869-c554-431a-8701-3f31525188c4.mp4

**Defaulting Quotas:**

https://user-images.githubusercontent.com/17727069/214517813-202ae717-c292-4c12-991b-59c57a988c68.mp4

daulting-image

**Which issue(s) this PR fixes**:

Fixes #5594 

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: modules/web/src/app/dynamic/enterprise/quotas/component.ts [hunk 1]
```diff
@@ -113,6 +113,21 @@ export class QuotasComponent implements OnInit {
...
+
+  hasMemoryOrDefaulted(element: QuotaDetails): boolean {
+    const quota = element?.quota;
+    return !!(quota?.memory || quota.memory === 0);
+  }
+
+  hasStorageOrDefaulted(element: QuotaDetails): boolean {
+    const quota = element?.quota;
+    return !!(quota?.storage || quota.storage === 0);
+  }
```
Comment (Waseem826) [inline modules/web/src/app/dynamic/enterprise/quotas/component.ts:129]: I think we can add these checks directly in the template because these only added in single place.
For example, for CPU it can be `element.quota && (element.quota.cpu || element.quota.cpu === 0)`
Wdyt?

File: modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts [hunk 2]
```diff
@@ -97,6 +97,19 @@ export class QuotaWidgetComponent implements OnInit, OnChanges, OnDestroy {
...
+    return !!(quota.cpu || quota.cpu === 0);
+  }
+  get hasMemoryOrDefaulted(): boolean {
+    const quota = this.quotaDetails?.quota;
+    return !!(quota.memory || quota.memory === 0);
+  }
+  get hasStorageOrDefaulted(): boolean {
+    const quota = this.quotaDetails?.quota;
+    return !!(quota.storage || quota.storage === 0);
+  }
```
Comment (Waseem826) [inline modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts:111]:
```suggestion
  get hasCpuQuota(): boolean {
    const quota = this.quotaDetails?.quota;
    return quota && !!(quota.cpu || quota.cpu === 0);
  }
  get hasMemoryQuota(): boolean {
    const quota = this.quotaDetails?.quota;
    return quota && !!(quota.memory || quota.memory === 0);
  }
  get hasStorageQuota(): boolean {
    const quota = this.quotaDetails?.quota;
    return quota && !!(quota.storage || quota.storage === 0);
  }
```

File: modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts [hunk 3]
```diff
@@ -200,12 +213,19 @@ export class QuotaWidgetComponent implements OnInit, OnChanges, OnDestroy {
...
-    const cpu = this._getPercentage(total.cpu, usage.cpu) ?? 0;
-    const memory = this._getPercentage(total.memory, usage.memory) ?? 0;
-    const storage = this._getPercentage(total.storage, usage.storage) ?? 0;
+    const cpu = this.isValidNumber(this._getPercentage(total.cpu, usage.cpu)) ?? 0;
+    const memory = this.isValidNumber(this._getPercentage(total.memory, usage.memory)) ?? 0;
+    const storage = this.isValidNumber(this._getPercentage(total.storage, usage.storage)) ?? 0;
     return {cpu, memory, storage};
   }
 
+  private isValidNumber(num: number): number {
```
Comment (Waseem826) [inline modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts:222]:
```suggestion
  private getValidNumber(num: number): number {
```

**Review by Waseem826 — CHANGES_REQUESTED** [review]
Some feedback. PTAL

**Review by Waseem826 — APPROVED** [review]
