### PR TITLE
Changing Provider after choosing Kubeadm Break the wizard

### LINKED ISSUE #5505: Changing Provider after choosing Kubeadm Break the wizard
**What is the problem?**
after choosing kubeadm in the first step in the wizard and try to chose another provider the wizard still the same wizard for kubeadm (no steps for settings and initial node shown)and an error showed repeatedly in the console 

**Expected behavior **
the user should be able to change the providers in the first step and the wizard's steps will changed according to the provider so when user chose kubeadm provider the wizard step will be 4 (no settings and initial node steps  for kubeadm) and when the user change the provider the steps suppose to be changed to 6 

**How to reproduce the issue?**
1- go to create cluster wizard
2- chose kubeadm the steps will be 4 steps (which is right )
3- chose another provider you will see that the steps number still the same didn't changed (it suppose to be 6)
4-notice the errors in the console

### PR DESCRIPTION
**Pull request by ahmadhamzh**
**What this PR does / why we need it**
fix displaying steps for wizard in case change provider after choosing kubeadm provider

**Which issue(s) this PR fixes**:
Fixes #5505 

**What type of PR is this?**
/kind bug

```release-note
NONE
```

```documentation
NONE
```

### CODE REVIEW

File: modules/web/src/app/core/services/wizard/wizard.ts [hunk 1]
```diff
@@ -33,22 +33,15 @@ export class WizardService {
     constructor(private _parent: WizardService) {}
 
     handleProviderChange(provider: NodeProvider): void {
+      this._parent._steps = steps;
```
Comment (Waseem826) [inline modules/web/src/app/core/services/wizard/wizard.ts:36]: We should call the setter method instead.
```suggestion
      this._parent.steps = steps;
```

File: modules/web/src/app/core/services/wizard/wizard.ts [hunk 2]
```diff
@@ -109,6 +102,10 @@ export class WizardService {
     this._clusterSpecService.provider = provider;
   }
 
+  getStepsForEditClusterTemplate(provider: NodeProvider) {
```
Comment (Waseem826) [inline modules/web/src/app/core/services/wizard/wizard.ts:105]: Wdyt?
```suggestion
  forceHandleProviderChange(provider: NodeProvider) {
```

**Review by Waseem826 — CHANGES_REQUESTED** [review]
Some feedback. PTAL

File: modules/web/src/app/core/services/wizard/wizard.ts (hunk 2 above)
Comment (ahmadhamzh) [reply modules/web/src/app/core/services/wizard/wizard.ts:105]: sounds better

**Review by Waseem826 — APPROVED** [review]
/approve
