### PR TITLE
Fix external cluster machine deployment health status icons and status

### LINKED ISSUE #4746: Fix external cluster machine deployment health status icons and status
**What is the problem, where is it and why is it an issue?**

Currently, when external cluster MD is different state show updated cluster icon and text

External Cluster MD states
"Provisioning" -> cluster machine deployment is being created.
"Running" -> cluster machine deployment is created and is fully usable
"Reconciling" -> some work is actively being done on the machine 
"Deleting" ->cluster md machine deployment is being deleted.
"Unknown" ->cluster md machine indicates undefined state.
"Error" -> last operation persformed on cluster  machine deployment failed (doesnt mean that md is unusable)
**Suggest how to fix it, if possible**

- [ ] used information from cluster response payload to to determine state of MD

### PR DESCRIPTION
**Pull request by KhizerRehan**
**What does this PR do / Why do we need it**:
This PR fix status icon and message for external cluster machine deployment based on which current `phase` of MD.

**Which issue(s) this PR fixes** :

Fixes #4746 

**Special notes for your reviewer**:

**Release Note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by KhizerRehan** [comment]
@imharshita

MD phase enum
https://github.com/kubermatic/dashboard/pull/4783/files#diff-f7765865162f4d8038338babc7740768572ecf6bb8d0b7f436520beba8bd47efR24

MD state struct
https://github.com/kubermatic/dashboard/pull/4783/files#diff-f7765865162f4d8038338babc7740768572ecf6bb8d0b7f436520beba8bd47efR120

File: src/app/shared/entity/external-machine-deployment.ts [hunk 1]
```diff
@@ -13,33 +13,40 @@
...
-import {StatusIcon} from '@shared/utils/health-status';
+import {HealthStatus, StatusIcon} from '@shared/utils/health-status';
 import {AKSMachineDeploymentCloudSpec} from './provider/aks';
 
 export enum AKSMachineDeploymentMode {
   User = 'User',
   System = 'System',
 }
 
+export enum ExternalClusterMDState {
```
Comment (Waseem826) [inline src/app/shared/entity/external-machine-deployment.ts:24]: Can we use `ExternalClusterState` enum since it contains all these values?

File: src/app/cluster/details/external-cluster/external-machine-deployment-details/component.ts [hunk 2]
```diff
@@ -130,12 +131,8 @@ export class ExternalMachineDeploymentDetailsComponent implements OnInit, OnDest
     this._unsubscribe.complete();
   }
 
-  getStatusColor(): string {
-    return ExternalMachineDeployment.getStatusIcon(this.machineDeployment);
-  }
-
-  getStatusMessage(): string {
-    return ExternalMachineDeployment.getStatusMessage(this.machineDeployment);
+  getHealthStatus(): HealthStatus {
```
Comment (Waseem826) [inline src/app/cluster/details/external-cluster/external-machine-deployment-details/component.ts:134]: Instead of this method, can we store health status in a field when `machineDeployment` is loaded?

File: src/app/shared/entity/external-machine-deployment.ts [hunk 3]
```diff
@@ -13,33 +13,40 @@
...
+  phase?: ExternalClusterMDPhase;
   cloud: ExternalMachineDeploymentCloudSpec;
 
-  static getStatusIcon(md: ExternalMachineDeployment): StatusIcon {
-    if (md?.deletionTimestamp) {
-      return StatusIcon.Error;
-    } else if (md?.status?.readyReplicas === md?.status?.replicas) {
-      return StatusIcon.Running;
+  static getExternalMachineDeploymentHealthStatus(md: ExternalMachineDeployment): HealthStatus {
+    if (md.phase && md.phase.state === ExternalClusterMDState.Deleting) {
```
Comment (Waseem826) [inline src/app/shared/entity/external-machine-deployment.ts:38]: Please use `switch` instead

File: src/app/shared/entity/external-machine-deployment.ts (hunk 1 above)
Comment (imharshita) [reply src/app/shared/entity/external-machine-deployment.ts:24]: its true, currently `ExternalClusterMDState` is a subset of `ExternalClusterState`. 
But I would recommend keeping them separate, to keep `Single Responsibility for data structures, as we don't want changes in one to affect the other.

File: src/app/shared/entity/external-machine-deployment.ts [hunk 4]
```diff
@@ -13,33 +13,40 @@
...
 export class ExternalMachineDeployment extends MachineDeployment {
+  phase?: ExternalClusterMDPhase;
   cloud: ExternalMachineDeploymentCloudSpec;
 
-  static getStatusIcon(md: ExternalMachineDeployment): StatusIcon {
-    if (md?.deletionTimestamp) {
-      return StatusIcon.Error;
-    } else if (md?.status?.readyReplicas === md?.status?.replicas) {
-      return StatusIcon.Running;
+  static getExternalMachineDeploymentHealthStatus(md: ExternalMachineDeployment): HealthStatus {
```
[the remark this answers is not in the document]
Comment (KhizerRehan) [reply src/app/shared/entity/external-machine-deployment.ts:37]: Than i guess we need to change for Normal KKP clusters MD method names. I just kept consistent with them.
thoughts? 
`src/app/cluster/details/cluster/machine-deployment-list/component.ts`

File: src/app/shared/entity/external-machine-deployment.ts (hunk 1 above)
Comment (KhizerRehan) [reply src/app/shared/entity/external-machine-deployment.ts:24]: yes! i used the same enum but later on i updated due to following reasons.
- Handling MD state with `ExternalClusterState` enum which IMO, was not better 
- If we want to use same enum -> better to rename `ExternalClusterState` to `HealthStateStatus` to be more generic than? thoughts?
- Seperation of concernes.

If still want to be used same i can update it.

File: src/app/shared/entity/external-machine-deployment.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (Waseem826) [reply src/app/shared/entity/external-machine-deployment.ts:37]: No, `getMachineDeploymentHealthStatus` is a global function but in this case `getExternalMachineDeploymentHealthStatus` is inside `ExternalMachineDeployment` class so it becomes a bit redundant to mention `ExternalMachineDeployment` twice.

File: src/app/shared/entity/external-machine-deployment.ts (hunk 1 above)
Comment (Waseem826) [reply src/app/shared/entity/external-machine-deployment.ts:24]: We can keep it as it is for now

File: src/app/cluster/details/external-cluster/external-machine-deployment-details/template.html [hunk 5]
```diff
@@ -22,8 +22,8 @@
     <mat-card-header>
       <mat-card-title class="machine-deployment-name">
         <i class="machine-deployment-health km-pointer"
-           [ngClass]="getStatusColor()"
-           [matTooltip]="getStatusMessage()"></i>
+           [matTooltip]="machineDeploymentHealthStatus.message"
+           [ngClass]="machineDeploymentHealthStatus.icon"></i>
```
Comment (Waseem826) [inline src/app/cluster/details/external-cluster/external-machine-deployment-details/template.html:26]:
```suggestion
           [matTooltip]="machineDeploymentHealthStatus?.message"
           [ngClass]="machineDeploymentHealthStatus?.icon"></i>
```
Because `machineDeploymentHealthStatus` is updated inside `subscribe`  so there's a chance that `machineDeploymentHealthStatus` can be `undefined` when this is rendered.

File: src/app/shared/entity/external-machine-deployment.ts [hunk 6]
```diff
@@ -13,33 +13,42 @@
...
+  phase?: ExternalClusterMDPhase;
   cloud: ExternalMachineDeploymentCloudSpec;
 
-  static getStatusIcon(md: ExternalMachineDeployment): StatusIcon {
-    if (md?.deletionTimestamp) {
-      return StatusIcon.Error;
-    } else if (md?.status?.readyReplicas === md?.status?.replicas) {
-      return StatusIcon.Running;
+  static getHealthStatus(md: ExternalMachineDeployment): HealthStatus {
+    switch (md.phase && md.phase.state) {
```
Comment (Waseem826) [inline src/app/shared/entity/external-machine-deployment.ts:38]:
```suggestion
    switch (md.phase?.state) {
```

**Review by Waseem826 — CHANGES_REQUESTED** [review]
Couple of small changes. PTAL

File: src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts [hunk 7]
```diff
@@ -49,6 +55,8 @@ export class UpdateExternalClusterMachineDeploymentDialogComponent extends BaseF
   readonly Controls = Controls;
   disableReplicaControl: boolean;
   versions: string[] = [];
+  versionsLoaded = false;
+  private _state = KubeletVersionState.Loading;
```
Comment (Waseem826) [inline src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts:59]: There's no need for this field to be private. This can be made public and `label` getter can be removed.
```suggestion
  versionsLabel = KubeletVersionState.Loading;
```

File: src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts [hunk 8]
```diff
@@ -108,7 +120,12 @@ export class UpdateExternalClusterMachineDeploymentDialogComponent extends BaseF
     this._externalMachineDeploymentService
       .machineDeploymentUpgrades(this.data.projectID, this.data.clusterID, this.data.machineDeployment?.id)
       .pipe(take(1))
-      .subscribe(this._setDefaultVersion.bind(this));
+      .subscribe((upgrades: MasterVersion[]) => {
+        this._setDefaultVersion(upgrades);
+        this.versionsLoaded = !!upgrades?.length;
```
Comment (Waseem826) [inline src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts:125]: IMO there's no need for `versionsLoaded` property and we can use `upgrades?.length` directly.

**Review by Waseem826 — CHANGES_REQUESTED** [review]

**Review by Waseem826 — APPROVED** [review]
/approve
