### PR TITLE
Fix Add Machine Deployment creation

### LINKED ISSUE #5366: Add a MachineDeployment is broken
### What happened
Adding a MachineDeployment is broken for AWS and KubeVirt, probably other providers too (on `dev`)
(maybe linked to https://github.com/kubermatic/dashboard/pull/5258).

### How to reproduce
1- Create an AWS cluster/KubeVirt cluster
2- Add a MachineDeployment

**AWS**
```
method: POST
:scheme: https
:authority: dev.kubermatic.io
:path: /api/v2/projects/f8vwtl5w7s/clusters/q8gxpcn7kx/machinedeployments
```

gives the following error:

```
URL: https://dev.kubermatic.io/api/v2/projects/f8vwtl5w7s/clusters/q8gxpcn7kx/machinedeployments
Status: 500
```
```
{
    "error": {
        "code": 500,
        "message": "failed to create machine deployment from template: unknown operating system"
    }
}
```

**KubeVirt**
Error
```
{
    "error": {
        "code": 500,
        "message": "failed to create machine deployment from template: no machine os was provided"
    }
}
```
 
Both errors related to OS provided.
Probably the same with all providers.

### PR DESCRIPTION
**Pull request by KhizerRehan**
**What this PR does / why we need it**:

This PR fixes the creation of Machine Deployment creation. In Case of "Add Machine Deployment" default OS is not selected but now based on provider it will select default OS.

[Source of truth for OS Support matrix](https://github.com/kubermatic/machine-controller/blob/main/docs/operating-system.md)

**Anexia:**
anexia

Other Providers "Defaults' Ubuntu:
Add-MD-creation

**Which issue(s) this PR fixes**:

Fixes #5366 

**What type of PR is this?**

/kind bug
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: modules/web/src/app/core/services/node-data/service.ts [hunk 1]
```diff
@@ -140,6 +141,18 @@ export class NodeDataService {
     } as NodeData;
   }
 
+  getDefaultOS(): OperatingSystem {
+    if (this.isProvider(NodeProvider.ANEXIA)) {
+      return OperatingSystem.Flatcar;
+    }
+    return OperatingSystem.Ubuntu;
```
Comment (ahmedwaleedmalik) [inline modules/web/src/app/core/services/node-data/service.ts:148]: What if the provider doesn't support Ubuntu? Instead of assuming and hardcoding I'd recommend that we should use `isOperatingSystemSupported` to check if it supports ubuntu and only in that case we should return `Ubuntu`. Something that we were already doing in the original method 

https://github.com/kubermatic/dashboard/blob/main/modules/web/src/app/node-data/component.ts#L434

File: modules/web/src/app/core/services/node-data/service.ts [hunk 2]
```diff
@@ -140,6 +141,18 @@ export class NodeDataService {
...
+  }
+
+  isProvider(...providers: NodeProvider[]): boolean {
+    const provider = this._clusterSpecService.provider;
```
Comment (ahmedwaleedmalik) [inline modules/web/src/app/core/services/node-data/service.ts:152]: Wouldn't this value be the same as ` this.provider`? Why did we change this?

File: modules/web/src/app/node-data/component.ts [hunk 3]
```diff
@@ -139,7 +139,7 @@ export class NodeDataComponent extends BaseFormValidator implements OnInit, OnDe
       ]),
       [Controls.Count]: this._builder.control(this._nodeDataService.nodeData.count),
       [Controls.DynamicConfig]: this._builder.control(this._nodeDataService.nodeData.dynamicConfig),
-      [Controls.OperatingSystem]: this._builder.control(this._getDefaultOS(), [Validators.required]),
+      [Controls.OperatingSystem]: this._builder.control({}, [Validators.required]),
```
Comment (ahmedwaleedmalik) [inline modules/web/src/app/node-data/component.ts:142]: Can we not use an `{}`; declare an object and instead start with a falsy value like null?

**Review by ahmedwaleedmalik — CHANGES_REQUESTED** [review]

**Comment by ahmedwaleedmalik** [comment]
@KhizerRehan is this PR really about `cleanup`? You have mentioned `/kind cleanup` in the description.

**Review by KhizerRehan — COMMENTED** [review]
Feedback Replies

**Comment by Waseem826** [comment]
I've taken over this PR on behalf of @KhizerRehan and pushed new changes. PTAL

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

Thank you for taking care of this guys 👍
