### PR TITLE
Fix issue to display empty placeholder in case no nodes exists

### LINKED ISSUE #4744: Display empty placeholder when no nodes exist
**What is the problem, where is it and why is it an issue?**
Currently, when no worker nodes exist instead of empty placeholder "No nodes available." it currently shows loading icon until any node exist to show table.

**Suggest how to fix it, if possible**

- [ ] Validate cluster health from cluster instead of Input from parent
- [ ] Update conditional checks to show loading icon

### How to reproduce
- Navigate to External cluster except "Custom" as UI doesn't display MD list in case of custom
- Navigate to MD details page
- When no nodes exist it was showing "Loading icon" so it should display "no nodes found"

### PR DESCRIPTION
**Pull request by KhizerRehan**
**What this PR does / why we need it**:
This PR fixes to display "no nodes available" when nodes list is empty but it was showing `loading` icon.

**Before:**
(Cluster was running && Nodes were empty)

before

**After:**

**Case-1:**
(Cluster was running && Nodes were empty)

after

**Case-2:**
(Cluster was running && Nodes list):

https://user-images.githubusercontent.com/17727069/185710814-21bf6813-b9e5-4c28-87e4-ab2668d84cf6.mp4

**Which issue(s) this PR fixes**:

Fixes #4744 

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

Issue was `isClusterRunning` was not passed in case of **MD details** page. Although cluster was in running state. Instead of passing cluster **state** from parent in details page NOW state is checked inside nodes list as we are already passing external cluster in both usages. which fixes the issue in following pages.

- Details page
- MD Details page

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Shows placeholder when no nodes exists inside external machine deployment details page
```

**Documentation**:

```documentation
None
```

### CODE REVIEW

File: src/app/cluster/details/external-cluster/external-node-list/component.ts [hunk 1]
```diff
@@ -72,11 +71,15 @@ export class ExternalNodeListComponent implements OnInit, OnChanges, OnDestroy {
...
-    return (_.isEmpty(this.nodes) && !this.isClusterRunning) || !this.isInitialized;
+    return (_.isEmpty(this.nodes) && !this.isRunning()) || !this.isInitialized;
   }
 
   hasNoData(): boolean {
-    return _.isEmpty(this.nodes) && this.isClusterRunning && this.isInitialized;
+    return _.isEmpty(this.nodes) && this.isRunning() && this.isInitialized;
+  }
+
+  isRunning(): boolean {
```
Comment (Waseem826) [inline src/app/cluster/details/external-cluster/external-node-list/component.ts:81]: This is the same method which was bound with `isClusterRunning` Input so how does this make the difference?

Comment (KhizerRehan) [reply src/app/cluster/details/external-cluster/external-node-list/component.ts:81]: Correct! At list details page same logic is used to check state from cluster and pass `isClusterRunning` passing as input where in case of MD details page -> `isClusterRunning` is never passed -> which makes !isClusterRunning -> truthy values and satisfies loader condition therefore it just keep displaying loading state in MD details page where nodes are shown

**Review by Waseem826 — APPROVED** [review]
/approve
