### PR TITLE
External cluster UI improvements and bug fixes

### LINKED ISSUE #4769: Show fields as disabled in case of AKS/EKS external until value is selected
- [ ] **EKS:**
Show subnets/security groups as disabled (not hidden) until VPC is selected

https://user-images.githubusercontent.com/17727069/182606795-53dc08d8-33f3-4d03-8cf7-2763921f1580.mp4

- [ ] **AKS:**
Show VMSize as disabled till Location is entered
Screenshot

### LINKED ISSUE #4818: Update external cluster md replicas disabled when upgrade not available
### What happened
Update external cluster MD replicas disabled when no upgrade is available for the Kubernetes version.
bug

### Expected behavior
- Updation of replicas should only be disabled when:
     - there is an upgrade available and the user selects the upgrade version 
- Updation of Kubernetes version should only be disabled when:
    - there is no upgrade available
    - user increases the replica count 

### Environment
- UI Version:
- API Version:
- Domain:
- Others:

### LINKED ISSUE #4829: Remove the warning for delete AKS/GKE external cluster dialog
### What happened
Remove the warning fro AKS/GKE externalcluster delete:
- [ ] remove the warning sign to information sign 
- [ ] keep the first line informing user of attached mds 
- [ ] remove the line `Please delete nodegroups....` 

** No changes required for EKS

delete

### Environment
- UI Version:
- API Version:
- Domain:
- Others:

### PR DESCRIPTION
**Pull request by KhizerRehan**
**What this PR does / why we need it**:

This PR fixes multiple issues related to external cluster.

**Which issue(s) this PR fixes**:

Fixes #4818 
Fixes #4769  
Fixes #4829 
FIxes: **Color code** for EKS cluster as AWS had same color code in dashboard pie chart distribution.

**What type of PR is this?**
/kind bug
/kind design

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
None
```
**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by KhizerRehan** [comment]
/hold 
https://github.com/kubermatic/dashboard/pull/4800/files is merged

File: src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts [hunk 1]
```diff
@@ -200,15 +209,35 @@ export class AKSClusterSettingsComponent
     } else {
       this.control(Controls.Location)
         .valueChanges.pipe(debounceTime(this._debounceTime))
-        .pipe(switchMap((location: string) => this._getAKSVmSizes(location)))
+        .pipe(tap(_ => this._clearVmSize()))
+        .pipe(filter(value => !!value))
+        .pipe(
+          switchMap((location: string) => {
+            this.control(Controls.VmSize).enable();
```
Comment (KhizerRehan) [inline src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts:216]: Info:
This part is intentional as control should only be disabled
**Point-1:**
- when no value existed (valid/invalid) value -> as soon user enters and API call is kicked off -> `loading` spinner will be shown on enabled state.
**Point-2**
- I didn't intentionally made `this.vmSizeLabel = VMSizeState.Loading;` since on enabled state
than label + `mat-error` shows -> `loading is required`  as label Name is used as label + mat-error too in `km-autocomplete` therefore a sort of `hack` is added to keep label same
When ready or Empty in enabled state

File: src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/component.ts [hunk 2]
```diff
@@ -31,11 +31,14 @@ import {ExternalMachineDeployment} from '@shared/entity/external-machine-deploym
   styleUrls: ['style.scss'],
 })
 export class ExternalClusterDeleteConfirmationComponent implements OnInit, OnDestroy, AfterContentChecked {
+  readonly Provider = ExternalClusterProvider;
   inputName = '';
   settings: AdminSettings;
   machineDeployments: ExternalMachineDeployment[] = [];
   warningMessage = '';
   isLoadingMachineDeployments = false;
+  clusterProvider: string;
```
Comment (Waseem826) [inline src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/component.ts:40]:
```suggestion
  clusterProvider: ExternalClusterProvider;
```

File: src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/template.html [hunk 3]
```diff
@@ -33,12 +34,21 @@
...
+       fxLayout="row"
+       fxLayoutAlign="start center">
+
+    <ng-container *ngIf="clusterProvider === Provider.EKS; else showInfoIcon">
+      <i class="km-icon-warning"></i>
+    </ng-container>
+
+    <ng-template #showInfoIcon>
+      <i class="km-icon-info"></i>
+    </ng-template>
```
Comment (Waseem826) [inline src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/template.html:49]:
```suggestion
    <i [ngClass]="clusterProvider === Provider.EKS ? 'km-icon-warning' : 'km-icon-info'"></i>
```

File: src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/template.html [hunk 4]
```diff
@@ -33,12 +34,21 @@
...
+
+    <div class="km-text">
```
Comment (Waseem826) [inline src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/template.html:51]: Should we add `*ngIf="warningMessage"` here?

File: src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts [hunk 5]
```diff
@@ -109,16 +111,21 @@ export class UpdateExternalClusterMachineDeploymentDialogComponent extends BaseF
       .get(Controls.KubeletVersion)
       .valueChanges.pipe(takeUntil(this._unsubscribe))
       .subscribe((value: string) => {
+        if (!this.upgradesAvailable) {
```
Comment (Waseem826) [inline src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts:114]: I think its better to add `filter` pipe instead

File: src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts [hunk 6]
```diff
@@ -70,6 +70,11 @@ enum Mode {
   User = 'User',
 }
 
+export enum VMSizeState {
+  Empty_OR_Ready = 'VM Size',
```
Comment (Waseem826) [inline src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts:74]: It could be just `Ready` I think and then we can use same value in both empty and ready state.

File: src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts [hunk 7]
```diff
@@ -103,11 +108,13 @@ export class AKSClusterSettingsComponent
   vmSizes: string[] = [];
   nodePoolVersionsForMD: string[] = [];
   kubernetesVersions: string[] = [];
+  vmSizeLabel: string = VMSizeState.Empty_OR_Ready;
```
Comment (Waseem826) [inline src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts:111]:
```suggestion
  vmSizeLabel = VMSizeState.Empty_OR_Ready;
```

File: src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html [hunk 8]
```diff
@@ -111,21 +111,24 @@
         Node pool Name must contain only lowercase letters and numbers, must be 12 or fewer characters.</mat-error>
     </mat-form-field>
 
-    <km-autocomplete label="VM Size"
+    <km-autocomplete label="{{vmSizeLabel}}"
```
Comment (Waseem826) [inline src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html:114]:
```suggestion
    <km-autocomplete [label]="vmSizeLabel"
```

File: src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts [hunk 9]
```diff
@@ -200,15 +208,31 @@ export class AKSClusterSettingsComponent
...
         });
+
       this._getAKSKubernetesVersions();
     }
   }
 
+  private _clearVmSize(): void {
+    this.vmSizeLabel = VMSizeState.Empty_OR_Ready;
+    this.vmSizes = [];
+    this.control(Controls.VmSize).disable();
```
Comment (Waseem826) [inline src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts:232]: Should we also clear the value?

**Review by Waseem826 — CHANGES_REQUESTED** [review]
Some feedback. PTAL

**Review by Waseem826 — APPROVED** [review]
