### PR TITLE
Fix cachin' too stronk

### LINKED ISSUE #3137: Caches too stronk
**What happened?**:
I upgraded my KKP from 2.15.6 to 2.16.3.

**What should happen?**:
The footer in the dashboard should say "v2.16.3". It didn't say anything anymore.

After some investigation it turns out that my browser was really, really keen on caching the version.json, which seems to have changed formats between 2.15 and 2.16.

Cachebusting would be great.

**How to reproduce?**:
- Install 2.15.6.
- Upgrade
- Refresh browser window

**Environment**
- UI Version: 2.16.3
- API Version: 2.16.3
- Domain: Captain
- Others: Firefox

### PR DESCRIPTION
**Pull request by floreks**
### What this PR does / why we need it
I have added `config` and `assets/config` directories to the no-cache zone to make sure all files there will be always taken from the server.

### Which issue(s) this PR fixes

Fixes #3137

### Release note

```release-note
NONE
```

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -70,10 +70,10 @@ func main() {
 }
 
 func handler(w http.ResponseWriter, r *http.Request) {
-	// disable caching for the main HTML page
-	if r.URL.Path == "/" || r.URL.Path == "/index.html" {
+	// disable caching for the root(index.html) and all config files
+	if r.URL.Path == "/" || isCacheDisabled(r.URL.Path) {
```
Comment (maciaszczykm) [inline main.go:74]: Can we add "/" to the method too?
