### PR TITLE
Fix cluster template bugs

### LINKED ISSUE #7632: Cluster template related bugs
### What happened

**GCP :**

when customize or editing a GCP cluster template, disk type and machine type values are not loaded

Image

**OS :**
"Skip Router Reconciliation " checkbox state is not persisted in cluster template which i think needs to be fixed.

Image

### PR DESCRIPTION
**Pull request by ahmadhamzh**
**What this PR does / why we need it**:
* fix disk types and machine types values are not loaded in cluster template
* fix "Skip Router Reconciliation " checkbox state is not persisted in cluster template

**Which issue(s) this PR fixes**:
Fixes #7632 

**What type of PR is this?**
/kind bug

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Fix disk types and machine types values are not loaded in cluster template for Google Cloud Provider
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

File: modules/web/src/app/node-data/basic/provider/gcp/component.ts [hunk 1]
```diff
@@ -266,7 +262,6 @@ export class GCPBasicNodeDataComponent extends BaseFormValidator implements OnIn
     this.diskTypes = [];
     this.selectedDiskType = '';
     this.diskTypeLabel = DiskTypeState.Empty;
-    this._diskTypesCombobox.reset();
```
Comment (Waseem826) [inline modules/web/src/app/node-data/basic/provider/gcp/component.ts:269]: This method indirectly triggers the `onDiskTypeChange` method so after removing this, it might not clear the `this._nodeDataService.nodeData.spec.cloud.gcp.diskType` value when you change the zone. Can you please verify that it still works?

**Review by Waseem826 — COMMENTED** [review]
Some feedback. PTAL

File: modules/web/src/app/node-data/basic/provider/gcp/component.ts (hunk 1 above)
Comment (ahmadhamzh) [reply modules/web/src/app/node-data/basic/provider/gcp/component.ts:269]: yeh i test it and it's working as expected, i will update some changes for the edit dialog
i don't see a reason to clear the value, we just need to update it with the default value, and the `_setDefaultDiskType` and `_setDefaultMachineType` are trigered when zone changes and the `onDiskTypeChange` and `onMachineTypeChange` method update the  `this._nodeDataService.nodeData.spec.cloud.gcp.diskType`

**Review by Waseem826 — APPROVED** [review]
/approve
