### PR TITLE
Remove the patch version in edit MD for EKS

### LINKED ISSUE #6334: EKS cluster k8s version list and edit value
### What happened
* the list of k8s versions don't have the 1.28 version.

image

* on edit MD the value to update the version must not have the patch release value (e.g 1.27.0 will not work wich is how we do it now, it must be 1.27).

### PR DESCRIPTION
**Pull request by ahmadhamzh**
**What this PR does / why we need it**:
in eks we shouldn't send the patch version for updating the machinedeployment
**Which issue(s) this PR fixes**:

Fixes #6334 

**What type of PR is this?**
/kind bug

```release-note
NONE
```

```documentation
NONE
```

### CODE REVIEW

File: modules/web/src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts [hunk 1]
```diff
@@ -137,13 +138,17 @@ export class UpdateExternalClusterMachineDeploymentDialogComponent extends BaseF
...
+    const endSliceParameter = 4;
     return {
       spec: {
         replicas: this.form.get(Controls.Replicas).value,
         template: {
           versions: {
-            kubelet: this.form.get(Controls.KubeletVersion).value,
+            // in EKS we shouldn't send the patch with the full version, only the major version.
+            kubelet: isEKSProvider
+              ? this.form.get(Controls.KubeletVersion).value.slice(0, endSliceParameter)
```
Comment (Waseem826) [inline modules/web/src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts:150]: I think we should use the `semver` package for parsing instead of using `slice` just to avoid any possibility of parsing error. For example, if version is `1.23-beta` or `1.100.1` then `slice` would not work as expected.

File: modules/web/src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts [hunk 2]
```diff
@@ -137,16 +139,24 @@ export class UpdateExternalClusterMachineDeploymentDialogComponent extends BaseF
...
         template: {
           versions: {
-            kubelet: this.form.get(Controls.KubeletVersion).value,
+            kubelet: kubeletVersion,
           },
         },
       } as ExternalMachineDeploymentSpecPatch,
     };
+
+    // in EKS we shouldn't send the patch with the full version, only the major version.
```
Comment (Waseem826) [inline modules/web/src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts:156]: Very small nitpick.
```suggestion
    // In EKS we shouldn't send the patch with the full version, only the major and minor versions.
```

**Review by Waseem826 — APPROVED** [review]
/approve
